name: convex_hull
description: Calculates the convex hull of a given set of points. Monotone chain is used as algorithm.
version: 1.0.1
homepage: https://github.com/defo10/convex-hull

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  logging: ^1.0.2